// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUAD_VOfQO87MIg-0K49UWZxg6oS59kI',
    appId: '1:476965124286:web:a8c1a97e128311380746ef',
    messagingSenderId: '476965124286',
    projectId: 'layerly-1c7d7',
    authDomain: 'layerly-1c7d7.firebaseapp.com',
    storageBucket: 'layerly-1c7d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5p6AKniusflI1GdA98eWUMdf4Ovvtick',
    appId: '1:476965124286:android:e81d3eac018d8a6d0746ef',
    messagingSenderId: '476965124286',
    projectId: 'layerly-1c7d7',
    storageBucket: 'layerly-1c7d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtyW96AM-Cvyid-eNZSQwjwvue9m1Pqo',
    appId: '1:476965124286:ios:6a3083c56bb334bb0746ef',
    messagingSenderId: '476965124286',
    projectId: 'layerly-1c7d7',
    storageBucket: 'layerly-1c7d7.firebasestorage.app',
    iosBundleId: 'com.layerly.layerly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtyW96AM-Cvyid-eNZSQwjwvue9m1Pqo',
    appId: '1:476965124286:ios:6a3083c56bb334bb0746ef',
    messagingSenderId: '476965124286',
    projectId: 'layerly-1c7d7',
    storageBucket: 'layerly-1c7d7.firebasestorage.app',
    iosBundleId: 'com.layerly.layerly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLUAD_VOfQO87MIg-0K49UWZxg6oS59kI',
    appId: '1:476965124286:web:2b8ba6596b5dce370746ef',
    messagingSenderId: '476965124286',
    projectId: 'layerly-1c7d7',
    authDomain: 'layerly-1c7d7.firebaseapp.com',
    storageBucket: 'layerly-1c7d7.firebasestorage.app',
  );
}
